### ISSUE TITLE
My custom theme doesn´t affect vscode preview presentation

### ISSUE THREAD

**Issue by rossii123** [marp-team/marp-vscode#100]
I have followed the instruction on how to add a custom theme in the readme file. But the css changes I write on my `your-theme.css` does not affect vscodes preview presentation. But my theme will appear if I export my .md file to pdf. 
My vscode version is: 
Version: 1.40.0
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.

**Comment by yhatt** [comment]
Are there any error outputs in VS Code developer console (`Ctrl/Cmd+Shift+I`)?

**Comment by rossii123** [comment]
I made it work on vscode version 1.39 but when we updated to 1.40 it stop working. We have tried on two computers.  The console output was: 
```
[Extension Host] Fetching theme CSS: /cool.css
console.ts:137 [Extension Host] Error: ENOENT: no such file or directory, open '/cool.css'
```
I disabled all my pluggins expect the marp extension when testing this.

**Comment by yhatt** [comment]
Thanks to provide useful infos. The path resolution might be broken since 1.40. (It seems to resolve the relative path from `/`)

**Comment by rossii123** [comment]
Nice! Then I will use the absolute path to the css file for now. The marp extension is awesome!

**Comment by yhatt** [comment]
We had used a messy hack for resolution logic so could not resolve this at the moment. I've sent feedback to VS Code (microsoft/vscode#84846).

**Comment by yhatt** [comment]
I've applied workaround in #103. It will be fixed in next patched version.

**Comment by yumoraby** [comment]
Has this issue been fixed, as whenever i update the CSS, i need to restart VSCode to see the changes. However changing inbuilt themes have no issues.

**Comment by Nopzen** [comment]
I get the same error now days as OP, dumping the info i have her, i got nothing in the output box from vscode:

**.vscode/settings.json**
```json
{
  "markdown.marp.themes": ["./theme/my-theme.css"]
}
```

**theme/my-theme.css**
```css
/* @theme my-theme */
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&display=swap');

:root {
  --background: rgb(0, 35, 61);
  --font: rgb(40, 40, 40);
}

section {
  background-color: white;
}

p,
h1,
h2,
h3 {
  font-family: 'Open Sans', sans-serif;
  color: var(--font);
  background-color: white;
}

h1 {
  font-weight: 300;
}
```

**slide.md**
```markdown
---
marp: true
theme: my-theme

# Your slide deck

Start writing!
```

Any suggestions @yhatt ?

**Comment by yhatt** [comment]
@Nopzen A triple-dashes line for closing [front-matter](https://jekyllrb.com/docs/front-matter/) has lacked in your Markdown.

```markdown
---
marp: true
theme: my-theme
---

# Your slide deck

Start writing!
```

**Comment by Nopzen** [comment]
@yhatt ah damn i missed that sorry for interrupting with this :D

**Comment by kongdd** [comment]
I have the same issue.
**my-theme:**
```css
/* my-theme.css */
@import 'default';

/* @theme marpit-theme */
/*Add "Page" prefix and total page number*/
/* section::after {
  content: 'Page ' attr(data-marpit-pagination) ' / ' attr(data-marpit-pagination-total);
} */

h1, h2, h3 {
  color: blue;
}

p {
  margin: 0em 0em 0.1em 0em
    /* top right bottom left */
}

.katex-display {
  display: block;
  line-height: 0.9;
  /* margin: 1em 0; */
  text-align: center;
}

blockquote {
  margin: 0.2em 0em 0.2em 0em
}
```

**markdown:**
```mk
---
marp: true
paginate: true
# size: 4:3
# header: 'Header space'
# footer: 'Footer space'
title: 'marp-theme-nordic-beamer demo slide'
# theme: nordic-beamer
theme: 'my-theme'
---

<!-- $size: 4:3 -->
<!-- page_number: true -->
<!-- Global style -->

# 位势高度与气压场
```

![image](https://user-images.githubusercontent.com/9815742/199141215-f76991c0-0a14-401b-a668-e9af679fc177.png)

**My vscode setting:**
```json
{
  "markdown.marp.themes": [
    "./themes/my-theme.css"
  ]
}
```
