### ISSUE TITLE
Support HTML comment as directive

### ISSUE THREAD

**Issue by gunta** [marp-team/marp-vscode#132]
Currently when one wants to add Marp to let's say a GitHub `README.md` one has to add 

```yaml
---
marp: true
theme: gaia
_class: lead
paginate: true
backgroundColor: #fff
---
```
which ends up rendering ugly in GitHub preview.

<img width="1011" alt="GitHubRendering" src="https://user-images.githubusercontent.com/657059/78508481-2ec14400-77c2-11ea-9f87-a8bc139ee58a.png">

It would be nice if HTML comment was also supported as directive, and not only Front-matter, so it doesn't gets ugly rendered by GitHub or any other Markdown renderer.
```yaml
<!--
marp: true
theme: gaia
_class: lead
paginate: true
backgroundColor: #fff
-->
```
