### ISSUE TITLE
Question - Can i do a4 documentation ?

### ISSUE THREAD

**Issue by melck** [marp-team/marp-vscode#43]
Hello, 

I like marp to do slide presentation. I want to go further and use it for internal documentation. I think to create a custom style for slide and A4 document and then when i want to do documentation i would change `$size` and custom style properties. 

Is it possible with marp ? Is it intented for usage like that ? Coud you give some advice ?

**Comment by yhatt** [comment]
Yes, Marp allows setting custom slide size by using theme CSS.

`$size` directive is only available for [the old Marp app](https://github.com/yhatt/marp), and cannot use in [Marp Next tools](https://github.com/marp-team/marp) by technical restriction. You have to use theme CSS whenever wanna change the size.

```css
/* theme-for-documentation.css */
/* @theme theme-for-documentation */

@import 'default';

section {
  /* A4 document size */
  width: 210mm;
  height: 297mm;
}

h1 {
  /* ...and your custom style properties... */
}
```

However, Marp for VS Code is not yet supported custom theme CSS (#39). Currently only [Marp CLI](https://github.com/marp-team/marp-cli) is available to use the custom theme.

```
marp --theme theme-for-documentation.css your-markdown.md --pdf
```

https://github.com/marp-team/marpit/issues/163 would be helpful too.
