### ISSUE TITLE
[Question] How can I customize pagination style?

### ISSUE THREAD

**Issue by retsohuang** [marp-team/marp-vscode#53]
Hello,
I want to use uncover theme's pagination style in Gaia theme, how to do that in YAML front-matter?

And how can I change pagination's position to the bottom center of the slide? The following configuration is not working.
```yaml
---
marp: true
theme: gaia
paginate: true
style: |
  section::after {
    text-align: bottom center;
  }
---
```
