### ISSUE TITLE
PDF export fails using vscodium and msft-edge-insider

### ISSUE THREAD

**Issue by jrappen** [marp-team/marp-vscode#84]
Could you test the pdf export with [vscodium](https://github.com/vscodium/vscodium) and [Microsoft Edge](https://www.microsoftedgeinsider.com) (Insider, Chromium)? Doesn't work for me.

```yaml
Microsoft Edge Insider:
  - v78.0.276.17 (x64, macOS)
vscodium:
  - v1.39.2
Marp:
  - v0.10.1
```
